// ============================================================================
// form-signing.functions.ts — Server functions: ký số Ed25519 & xác thực.
//
// - ensureSigningKey(): sinh cặp khoá Ed25519 thật (nếu bảng đang giữ khoá
//   placeholder từ migration) và trả về key_id + public_key_b64.
// - signSubmission({ submission_id, note? }): kiểm quyền → hash payload →
//   ký Ed25519 → insert form_submission_signature → update form_submission.
// - verifySubmission({ submission_id }): PUBLIC — không cần auth. Trả về
//   trạng thái xác thực (hash match? chữ ký hợp lệ?) để hiển thị ở /verify.
// ============================================================================
import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import * as ed from "@noble/ed25519";
import { sha512 } from "@noble/hashes/sha2.js";
import { canonicalize, hashPayload, type SignablePayload } from "@/lib/mirats/sig-canonical";
import { compileField, parseCompiledSchema, resolveSubmissionFields } from "@/lib/mirats/form-schema";
import { validateForm } from "@/lib/mirats/form-visibility";

// Bắt buộc cho @noble/ed25519 v3 khi chạy trên môi trường không có SHA-512 native.

ed.hashes.sha512 = (msg: Uint8Array) => sha512(msg);

function b64ToBytes(b64: string): Uint8Array {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function bytesToB64(bytes: Uint8Array): string {
  let s = "";
  for (const b of bytes) s += String.fromCharCode(b);
  return btoa(s);
}
function hexToBytes(hex: string): Uint8Array {
  const clean = hex.replace(/[^0-9a-f]/gi, "");
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(clean.substr(i * 2, 2), 16);
  return out;
}

/** Sinh (hoặc lấy) cặp khoá Ed25519 hoạt động. Placeholder từ migration sẽ bị thay. */
async function getActiveKey(admin: Awaited<ReturnType<typeof import("@/integrations/supabase/client.server").supabaseAdmin.from>> extends never ? never : any) {
  const { data: rows, error } = await admin
    .from("system_signing_key")
    .select("*")
    .eq("active", true)
    .order("created_at", { ascending: false })
    .limit(1);
  if (error) throw new Error(`Không đọc được khoá ký: ${error.message}`);
  const row = rows?.[0];
  const isPlaceholder = row?.note?.startsWith("placeholder");
  if (row && !isPlaceholder) return row;

  // Sinh cặp khoá thật
  const priv = ed.utils.randomSecretKey();
  const pub = await ed.getPublicKeyAsync(priv);
  const insertRow = {
    alg: "Ed25519",
    public_key_b64: bytesToB64(pub),
    private_key_b64: bytesToB64(priv),
    active: true,
    note: "auto-generated by ensureSigningKey()",
  };
  // Vô hiệu hoá placeholder trước, sau đó insert
  if (row) {
    await admin.from("system_signing_key").update({ active: false, rotated_at: new Date().toISOString() }).eq("id", row.id);
  }
  const { data: created, error: insErr } = await admin
    .from("system_signing_key").insert(insertRow).select("*").single();
  if (insErr) throw new Error(`Không tạo được khoá ký: ${insErr.message}`);
  return created;
}

/** Ensure key — có thể gọi thủ công từ admin để "kích hoạt" hệ thống ký. */
export const ensureSigningKey = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { data: roles } = await context.supabase
      .from("user_roles").select("role").eq("user_id", context.userId);
    const isAdmin = (roles ?? []).some((r) => r.role === "admin");
    if (!isAdmin) throw new Error("Chỉ admin mới được sinh khoá ký.");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const key = await getActiveKey(supabaseAdmin);
    return { key_id: key.id as string, public_key_b64: key.public_key_b64 as string, alg: key.alg as string };
  });

/** Lấy payload có thể ký từ submission (server-side). */
async function buildSignablePayload(admin: any, submissionId: string): Promise<{ payload: SignablePayload; sub: any }> {
  const { data: sub, error } = await admin
    .from("form_submission")
    .select("id, template_id, template_code, template_version_id, don_vi_id, thiet_bi_id, ky_bao_cao, tieu_de, data")
    .eq("id", submissionId)
    .single();
  if (error || !sub) throw new Error("Không tìm thấy biên bản.");
  const payload: SignablePayload = {
    submission_id: sub.id,
    template_id: sub.template_id,
    template_code: sub.template_code,
    template_version_id: sub.template_version_id ?? null,
    don_vi_id: sub.don_vi_id ?? null,
    thiet_bi_id: sub.thiet_bi_id ?? null,
    ky_bao_cao: sub.ky_bao_cao ?? null,
    tieu_de: sub.tieu_de ?? null,
    data: (sub.data ?? {}) as Record<string, unknown>,
    signatures_visual: null, // v1 chưa gộp chữ ký tay vào hash
  };
  return { payload, sub };
}


/** Core: thực hiện ký (đã kiểm tra quyền/OTP bên ngoài). */
async function performSign(
  userId: string,
  submission_id: string,
  signer_role: "nguoi_thuc_hien" | "phu_trach" | "admin",
  note: string | null | undefined,
  userSupabase: { from: (t: string) => { select: (c: string) => { eq: (k: string, v: unknown) => { maybeSingle: () => Promise<{ data: { ho_ten?: string } | null }> } } } },
) {
  const { data: prof } = await userSupabase
    .from("profiles").select("ho_ten").eq("id", userId).maybeSingle();

  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const key = await getActiveKey(supabaseAdmin);
  const { payload, sub } = await buildSignablePayload(supabaseAdmin, submission_id);

  // Validate required / required_if
  try {
    const { data: rows } = await supabaseAdmin
      .from("form_field").select("*").eq("template_id", sub.template_id).order("position");
    let versionSchema = null;
    if (sub.template_version_id) {
      const { data: ver } = await supabaseAdmin
        .from("form_template_version").select("compiled_schema").eq("id", sub.template_version_id).maybeSingle();
      versionSchema = parseCompiledSchema(ver?.compiled_schema);
    }
    const { data: subFull } = await supabaseAdmin
      .from("form_submission").select("template_snapshot").eq("id", submission_id).maybeSingle();
    const { fields } = resolveSubmissionFields({
      snapshot: parseCompiledSchema(subFull?.template_snapshot),
      versionSchema,
      currentFields: (rows ?? []).map((f, i) => compileField(f, i)),
    });
    const errs = validateForm(fields, (sub.data ?? {}) as Record<string, unknown>);
    if (errs.length > 0) {
      throw new Error("Không thể ký — biên bản thiếu dữ liệu bắt buộc:\n" + errs.map((e) => `• ${e.message}`).join("\n"));
    }
  } catch (e) {
    if (e instanceof Error && e.message.startsWith("Không thể ký")) throw e;
  }

  const hashHex = hashPayload(payload);
  const msg = new TextEncoder().encode(hashHex);
  const priv = b64ToBytes(key.private_key_b64);
  const sigBytes = await ed.signAsync(msg, priv);

  const { error: insErr } = await supabaseAdmin.from("form_submission_signature").insert({
    submission_id,
    signer_user_id: userId,
    signer_role,
    signer_name: prof?.ho_ten ?? null,
    content_hash: hashHex,
    signature_b64: bytesToB64(sigBytes),
    key_id: key.id,
    alg: "Ed25519",
    note: note ?? null,
  });
  if (insErr) throw new Error(`Không lưu được chữ ký: ${insErr.message}`);

  await supabaseAdmin.from("form_submission").update({
    content_hash: hashHex,
    signed_by: userId,
    signed_at: new Date().toISOString(),
  }).eq("id", submission_id);

  return { ok: true, content_hash: hashHex, signer_role };
}

const SignInput = z.object({
  submission_id: z.string().uuid(),
  signer_role: z.enum(["nguoi_thuc_hien", "phu_trach", "admin"]).default("phu_trach"),
  note: z.string().max(500).optional(),
});

export const signSubmission = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: unknown) => SignInput.parse(data))
  .handler(async ({ data, context }) => {
    const { data: roles } = await context.supabase
      .from("user_roles").select("role").eq("user_id", context.userId);
    const roleList = (roles ?? []).map((r) => r.role);
    if (!roleList.length) throw new Error("Tài khoản không có vai trò để ký.");
    return performSign(context.userId, data.submission_id, data.signer_role, data.note, context.supabase as never);
  });

// ── OTP: yêu cầu mã & ký bằng mã (P4 Form Designer) ─────────────────────────
function genOtp(): string {
  // 6 chữ số, an toàn về entropy
  const buf = new Uint8Array(4);
  crypto.getRandomValues(buf);
  const n = ((buf[0] << 24) | (buf[1] << 16) | (buf[2] << 8) | buf[3]) >>> 0;
  return String(n % 1000000).padStart(6, "0");
}

async function sha256Hex(s: string): Promise<string> {
  const h = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return Array.from(new Uint8Array(h)).map((b) => b.toString(16).padStart(2, "0")).join("");
}

const RequestOtpInput = z.object({
  submission_id: z.string().uuid(),
  channel: z.enum(["telegram"]).default("telegram"),
  signer_role: z.enum(["nguoi_thuc_hien", "phu_trach", "admin"]).default("phu_trach"),
  note: z.string().max(500).optional(),
});

export const requestSignOtp = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: unknown) => RequestOtpInput.parse(data))
  .handler(async ({ data, context }) => {
    const { data: roles } = await context.supabase
      .from("user_roles").select("role").eq("user_id", context.userId);
    if (!(roles ?? []).length) throw new Error("Tài khoản không có vai trò để ký.");

    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    // Lấy chat Telegram của user
    const { data: subs } = await supabaseAdmin
      .from("telegram_subscriber")
      .select("chat_id, ten")
      .eq("user_id", context.userId)
      .eq("active", true)
      .eq("la_nhom", false)
      .limit(1);
    const chat = subs?.[0];
    if (!chat) {
      throw new Error("Bạn chưa liên kết Telegram cá nhân (không phải nhóm). Vào Cài đặt → Telegram để đăng ký chat_id trước khi ký bằng OTP.");
    }

    const code = genOtp();
    const code_hash = await sha256Hex(code);
    const expires_at = new Date(Date.now() + 5 * 60 * 1000).toISOString();

    // Huỷ các OTP cũ chưa dùng cho cặp (user, submission)
    await supabaseAdmin.from("form_sign_otp")
      .update({ consumed_at: new Date().toISOString() })
      .eq("user_id", context.userId)
      .eq("submission_id", data.submission_id)
      .is("consumed_at", null);

    const { error: insErr } = await supabaseAdmin.from("form_sign_otp").insert({
      submission_id: data.submission_id,
      user_id: context.userId,
      channel: data.channel,
      code_hash,
      signer_role: data.signer_role,
      note: data.note ?? null,
      expires_at,
    });
    if (insErr) throw new Error(`Không tạo được OTP: ${insErr.message}`);

    // Meta biên bản
    const { data: sub } = await supabaseAdmin
      .from("form_submission").select("tieu_de, template_code, ky_bao_cao").eq("id", data.submission_id).maybeSingle();

    const { sendMessage, escapeHtml } = await import("@/lib/telegram.server");
    const title = sub?.tieu_de ?? sub?.template_code ?? "Biên bản";
    const text = [
      `🔐 <b>Mã OTP ký số MIRATS</b>`,
      `Biên bản: <b>${escapeHtml(String(title))}</b>${sub?.ky_bao_cao ? ` · Kỳ ${escapeHtml(String(sub.ky_bao_cao))}` : ""}`,
      `Mã: <code>${code}</code>`,
      `Hạn dùng: <b>5 phút</b> · Vai trò: ${escapeHtml(data.signer_role)}`,
      `Nếu không phải bạn yêu cầu, bỏ qua tin nhắn này.`,
    ].join("\n");
    try {
      await sendMessage(chat.chat_id, text);
    } catch (e) {
      throw new Error(`Không gửi được OTP qua Telegram: ${e instanceof Error ? e.message : String(e)}`);
    }

    return { ok: true, channel: data.channel, sent_to: `Telegram (${chat.ten ?? chat.chat_id})`, expires_at };
  });

const SignWithOtpInput = z.object({
  submission_id: z.string().uuid(),
  code: z.string().regex(/^\d{6}$/, "OTP phải là 6 chữ số"),
});

export const signSubmissionWithOtp = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((data: unknown) => SignWithOtpInput.parse(data))
  .handler(async ({ data, context }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: rows } = await supabaseAdmin
      .from("form_sign_otp")
      .select("*")
      .eq("user_id", context.userId)
      .eq("submission_id", data.submission_id)
      .is("consumed_at", null)
      .order("created_at", { ascending: false })
      .limit(1);
    const row = rows?.[0];
    if (!row) throw new Error("Không có OTP đang chờ. Hãy yêu cầu mã mới.");
    if (new Date(row.expires_at).getTime() < Date.now()) {
      await supabaseAdmin.from("form_sign_otp").update({ consumed_at: new Date().toISOString() }).eq("id", row.id);
      throw new Error("OTP đã hết hạn. Hãy yêu cầu mã mới.");
    }
    if ((row.attempts ?? 0) >= 5) {
      await supabaseAdmin.from("form_sign_otp").update({ consumed_at: new Date().toISOString() }).eq("id", row.id);
      throw new Error("Sai OTP quá số lần cho phép. Hãy yêu cầu mã mới.");
    }
    const codeHash = await sha256Hex(data.code);
    if (codeHash !== row.code_hash) {
      await supabaseAdmin.from("form_sign_otp").update({ attempts: (row.attempts ?? 0) + 1 }).eq("id", row.id);
      throw new Error(`OTP không đúng. Còn ${5 - ((row.attempts ?? 0) + 1)} lần thử.`);
    }
    // Đánh dấu đã dùng trước khi ký (chống replay)
    await supabaseAdmin.from("form_sign_otp").update({ consumed_at: new Date().toISOString() }).eq("id", row.id);

    return performSign(
      context.userId,
      data.submission_id,
      row.signer_role as "phu_trach" | "nguoi_thuc_hien" | "admin",
      row.note,
      context.supabase as never,
    );
  });


/** Verify PUBLIC — không cần đăng nhập, chỉ trả về trạng thái xác thực. */
const VerifyInput = z.object({ submission_id: z.string().uuid() });

export const verifySubmission = createServerFn({ method: "POST" })
  .inputValidator((data: unknown) => VerifyInput.parse(data))
  .handler(async ({ data }) => {
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    const { data: sigs } = await supabaseAdmin
      .from("form_submission_signature")
      .select("id, signer_name, signer_role, signed_at, content_hash, signature_b64, key_id, alg")
      .eq("submission_id", data.submission_id)
      .order("signed_at", { ascending: true });

    // Meta biên bản (public: chỉ những trường bất biến để hiển thị)
    const { data: sub } = await supabaseAdmin
      .from("form_submission")
      .select("id, template_code, tieu_de, ky_bao_cao, status, submitted_at, signed_at, don_vi:dm_don_vi(ten)")
      .eq("id", data.submission_id)
      .maybeSingle();

    // Tính lại hash hiện tại + canonical preview
    let currentHash: string | null = null;
    let canonicalPreview: string | null = null;
    try {
      const { payload } = await buildSignablePayload(supabaseAdmin, data.submission_id);
      currentHash = hashPayload(payload);
      const s = canonicalize(payload);
      canonicalPreview = s.length > 2000 ? s.slice(0, 2000) + "…" : s;
    } catch { /* noop */ }

    // Signed URL của PDF (nếu đã xuất)
    let pdfUrl: string | null = null;
    try {
      const key = `submissions/${data.submission_id}.pdf`;
      const { data: signed } = await supabaseAdmin.storage.from("form-pdf").createSignedUrl(key, 3600);
      if (signed?.signedUrl) pdfUrl = signed.signedUrl;
    } catch { /* file chưa tồn tại */ }

    const meta = sub ? {
      id: sub.id,
      template_code: sub.template_code,
      tieu_de: sub.tieu_de,
      ky_bao_cao: sub.ky_bao_cao,
      status: sub.status,
      submitted_at: sub.submitted_at,
      signed_at: sub.signed_at,
      don_vi_ten: (sub.don_vi as { ten?: string } | null)?.ten ?? null,
    } : null;

    if (!sigs || sigs.length === 0) {
      return {
        found: false, valid: false, current_hash: currentHash,
        canonical_preview: canonicalPreview, pdf_url: pdfUrl, meta,
        signatures: [] as any[],
      };
    }

    const keyIds = Array.from(new Set(sigs.map((s) => s.key_id)));
    const { data: keys } = await supabaseAdmin
      .from("system_signing_key").select("id, public_key_b64, alg").in("id", keyIds);
    const keyMap = new Map((keys ?? []).map((k) => [k.id, k]));

    const results = [] as Array<{
      id: string; signer_name: string | null; signer_role: string; signed_at: string;
      content_hash: string; matches_current: boolean; signature_valid: boolean; alg: string; key_id: string;
    }>;

    for (const s of sigs) {
      const k = keyMap.get(s.key_id);
      let sigValid = false;
      if (k) {
        try {
          const msg = new TextEncoder().encode(s.content_hash);
          const sigBytes = b64ToBytes(s.signature_b64);
          const pubBytes = b64ToBytes(k.public_key_b64);
          sigValid = await ed.verifyAsync(sigBytes, msg, pubBytes);
        } catch { sigValid = false; }
      }
      results.push({
        id: s.id, signer_name: s.signer_name, signer_role: s.signer_role, signed_at: s.signed_at,
        content_hash: s.content_hash,
        matches_current: currentHash != null && s.content_hash === currentHash,
        signature_valid: sigValid, alg: s.alg, key_id: s.key_id,
      });
    }

    const allValid = results.every((r) => r.signature_valid && r.matches_current);
    return {
      found: true, valid: allValid, current_hash: currentHash,
      canonical_preview: canonicalPreview, pdf_url: pdfUrl, meta,
      signatures: results,
    };
  });
