export const Constants = {
  public: {
    Enums: {
      app_role: [
        "admin",
        "phong_kt",
        "phu_trach_dv",
        "ktv",
        "readonly",
        "quan_ly_du_an",
        "to_truong",
      ],
      bao_cao_annotation_loai: ["bao_tri", "su_co", "thay_doi", "ghi_chu"],
      change_request_loai: [
        "cay.delete_node",
        "cay.restore_node",
        "cay.hard_delete_node",
        "cay.reorg",
        "thiet_bi.change_model",
        "thiet_bi.change_don_vi",
        "he_thong.change_nhom",
        "he_thong.change_don_vi",
        "danh_muc.merge",
        "danh_muc.deactivate",
        "role.grant",
        "role.revoke",
        "thiet_bi.propose_field",
        "he_thong.propose_field",
        "dm.propose_new",
      ],
      change_request_status: ["pending", "approved", "rejected", "cancelled", "applied_failed"],
      cong_van_lien_ket_loai: ["tra_loi", "can_cu", "lien_quan", "dinh_kem"],
      cong_van_loai: ["den", "di", "to_trinh", "bao_cao", "quyet_dinh", "khac"],
      cong_van_trang_thai: [
        "moi",
        "dang_xu_ly",
        "cho_duyet",
        "da_duyet",
        "da_phat_hanh",
        "hoan_tat",
        "huy",
      ],
      cong_viec_trang_thai: ["chua_bat_dau", "dang_lam", "cho_duyet", "hoan_thanh", "qua_han"],
      don_vi_code: ["CRA", "CLA", "THO", "PCA", "PBA", "PLK"],
      dot_bao_duong_hm_ket_qua: ["dat", "khong_dat", "khac"],
      dot_bao_duong_hm_nguon: ["kt_khoi_tao", "don_vi_bo_sung"],
      dot_bao_duong_hm_trang_thai: ["chua_bat_dau", "dang_lam", "hoan_thanh", "khong_thuc_hien"],
      dot_bao_duong_trang_thai: ["nhap", "mo", "dang_thuc_hien", "dong", "huy"],
      du_an_trang_thai: ["moi", "dang_thuc_hien", "tam_dung", "hoan_thanh", "huy"],
      form_field_kind: [
        "text",
        "textarea",
        "number",
        "date",
        "datetime",
        "select",
        "multiselect",
        "checkbox",
        "file",
        "user_ref",
        "don_vi_ref",
        "thiet_bi_ref",
        "measure",
        "before_after",
        "rating",
        "radio",
        "photo",
        "signature",
        "geo",
        "duration",
        "table",
        "linh_kien_ref",
        "vat_tu_ref",
        "he_thong_thanh_phan_ref",
        "computed",
        "heading",
        "note",
        "divider",
        "section_repeat",
      ],
      form_ket_qua: ["dat", "khong_dat", "khong_ap_dung"],
      form_result_kind: ["so", "dat_khong_dat", "chon", "text"],
      form_submission_status: ["draft", "submitted", "approved", "returned"],
      form_template_version_status: ["draft", "published", "retired"],
      form_thiet_bi_mode: ["none", "single", "multi"],
      node_note_type: ["he_thong", "thanh_phan"],
      notification_loai: [
        "ticket_moi",
        "ticket_cap_nhat",
        "ticket_binh_luan",
        "tin_nhan_moi",
        "he_thong",
        "cv_moi",
        "cv_cap_nhat",
      ],
      thiet_bi_tep_loai: ["hinh_anh", "tai_lieu"],
      ticket_loai: ["cap_tai_khoan", "doi_quyen", "reset_mat_khau", "bao_loi", "khac"],
      ticket_trang_thai: ["moi", "dang_xu_ly", "cho_phan_hoi", "hoan_thanh", "tu_choi", "dong"],
      ticket_uu_tien: ["thap", "trung_binh", "cao", "khan"],
    },
  },
};
