import {
  Eye,
  Pencil,
  Trash2,
  History,
  Paperclip,
  Copy,
  ArrowUp,
  ArrowDown,
  ChevronsUpDown,
  Filter,
  FilterX,
  Settings2,
  CheckCircle2,
  AlertTriangle,
  XCircle,
  Info,
  HardDrive,
  Network,
  User,
  FileText,
  LayoutDashboard,
  RefreshCw,
  RotateCcw,
  Undo2,
  ChevronRight,
  ChevronDown,
  Maximize2,
  SlidersHorizontal,
  Search,
  X,
  Check,
  Clock,
  Calendar,
  Download,
  Printer,
  Link as LinkIcon,
  ShieldCheck,
  ShieldAlert,
  AlertCircle,
  HelpCircle,
  Activity,
  PauseCircle,
  AlertOctagon,
  CalendarClock,
  CalendarX,
  BadgeAlert,
  FileWarning,
  Flame,
  HeartPulse,
  Gauge,
  Wrench,
  TrendingUp,
  TrendingDown,
  Repeat2,
  Radio,
  ClipboardCheck,
  ArrowRightLeft,
  Sparkles,
  ArrowRight,
  Trophy,
  Zap,
  BarChart3,
  ListTree,
  GitFork,
  List,
  ClipboardList,
} from "lucide-react";

export const ICON_REGISTRY = {
  // --- Actions ---
  "action.view": Eye,
  "action.edit": Pencil,
  "action.delete": Trash2,
  "action.history": History,
  "action.attach": Paperclip,
  "action.copy": Copy,
  "action.download": Download,
  "action.print": Printer,
  "action.link": LinkIcon,
  "action.search": Search,
  "action.close": X,
  "action.confirm": Check,
  "action.sync": ArrowRightLeft,
  "action.repeat": Repeat2,
  "action.next": ArrowRight,

  // --- Table Controls ---
  "table.sortAsc": ArrowUp,
  "table.sortDesc": ArrowDown,
  "table.sortNone": ChevronsUpDown,
  "table.filter": Filter,
  "table.filterActive": FilterX,
  "table.settings": Settings2,
  "table.maximize": Maximize2,
  "table.reset": RotateCcw,
  "table.expand": ChevronRight,
  "table.collapse": ChevronDown,

  // --- Status & Feedback ---
  "status.success": CheckCircle2,
  "status.warning": AlertTriangle,
  "status.danger": XCircle,
  "status.error": AlertCircle,
  "status.info": Info,
  "status.help": HelpCircle,
  "status.loading": RefreshCw,
  "status.undo": Undo2,
  "status.critical": AlertOctagon,
  "status.alert": BadgeAlert,
  "status.warning_alt": FileWarning,
  "status.emergency": Flame,
  "status.health": HeartPulse,
  "status.maintenance": Wrench,
  "status.sparkle": Sparkles,
  "status.trophy": Trophy,
  "status.power": Zap,

  // --- Entities ---
  "entity.asset": HardDrive,
  "entity.system": Network,
  "entity.user": User,
  "entity.document": FileText,
  "entity.dashboard": LayoutDashboard,
  "entity.history": Clock,
  "entity.calendar": Calendar,
  "entity.calendarClock": CalendarClock,
  "entity.calendarX": CalendarX,
  "entity.security": ShieldCheck,
  "entity.securityAlert": ShieldAlert,
  "entity.activity": Activity,
  "entity.pause": PauseCircle,
  "entity.gauge": Gauge,
  "entity.trendingUp": TrendingUp,
  "entity.trendingDown": TrendingDown,
  "entity.radio": Radio,
  "entity.check": ClipboardCheck,
  "entity.chart": BarChart3,
  "entity.tree": ListTree,
  "entity.fork": GitFork,
  "entity.list": List,
  "entity.checklist": ClipboardList,
} as const;

export type IconName = keyof typeof ICON_REGISTRY;
